import HomeNavigationMenu from "../HomeNavigation"
import Footer from "../Footer"

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-muted dark:bg-neutral-900">
      <HomeNavigationMenu />
      <div className="container mx-auto max-w-3xl px-4 py-16 md:px-6">
        <h1 className="text-2xl font-semibold tracking-tight text-gray-900 dark:text-gray-100 mb-2">
          Terms of Service
        </h1>
        <p className="text-sm text-gray-600 dark:text-gray-400 mb-8">
          Last updated: July 20, 2026
        </p>
        <div className="prose prose-gray dark:prose-invert max-w-none space-y-8 text-gray-800 dark:text-gray-200">
          <section>
            <h2 className="text-xl font-medium text-gray-800 dark:text-gray-200 mb-3">1. Acceptance of Terms</h2>
            <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed">
              By accessing or using AI Listing (&ldquo;the Service&rdquo;), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service. We may update these terms from time to time, and continued use constitutes acceptance of any changes.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-medium text-gray-800 dark:text-gray-200 mb-3">2. Description of Service</h2>
            <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed">
              AI Listing provides an AI-powered platform that generates Amazon product listings, including titles, bullet points, A+ Content, and backend search terms. The Service is intended for sellers and agencies looking to streamline their Amazon content creation process.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-medium text-gray-800 dark:text-gray-200 mb-3">3. User Accounts</h2>
            <ul className="space-y-2 text-sm text-gray-600 dark:text-gray-400 list-disc pl-5">
              <li>You must provide accurate and complete information when creating an account.</li>
              <li>You are responsible for maintaining the confidentiality of your login credentials.</li>
              <li>You must notify us immediately of any unauthorized use of your account.</li>
              <li>You must be at least 18 years old to use the Service.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-medium text-gray-800 dark:text-gray-200 mb-3">4. Subscriptions & Payment</h2>
            <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed">
              Our Service is offered on a subscription basis. By selecting a paid plan, you agree to pay the fees associated with that plan. All fees are non-refundable except as required by law. We reserve the right to change pricing with 30 days&apos; notice. Free trials may be subject to additional terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-medium text-gray-800 dark:text-gray-200 mb-3">5. Acceptable Use</h2>
            <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed">
              You agree not to use the Service to:
            </p>
            <ul className="mt-2 space-y-2 text-sm text-gray-600 dark:text-gray-400 list-disc pl-5">
              <li>Generate content that violates Amazon&apos;s listing policies or any applicable laws.</li>
              <li>Create listings for counterfeit, illegal, or prohibited products.</li>
              <li>Attempt to reverse-engineer, scrape, or disrupt our platform.</li>
              <li>Resell or redistribute the Service without prior written consent.</li>
              <li>Use automated means to exceed usage limits or bypass restrictions.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-medium text-gray-800 dark:text-gray-200 mb-3">6. Intellectual Property</h2>
            <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed">
              The AI Listing platform, including its code, design, and underlying AI models, is our exclusive property. You retain ownership of the product information you provide. Content generated by the Service based on your inputs is yours to use commercially on Amazon. We may use anonymized usage data to improve our AI models.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-medium text-gray-800 dark:text-gray-200 mb-3">7. Disclaimer of Warranties</h2>
            <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed">
              The Service is provided &ldquo;as is&rdquo; without warranties of any kind. We do not guarantee that AI-generated content will comply with Amazon&apos;s policies in every case. Users are responsible for reviewing and ensuring their listings meet Amazon&apos;s requirements before publishing.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-medium text-gray-800 dark:text-gray-200 mb-3">8. Limitation of Liability</h2>
            <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed">
              To the fullest extent permitted by law, AI Listing shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service. Our total liability is limited to the amount you paid us in the 12 months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-medium text-gray-800 dark:text-gray-200 mb-3">9. Termination</h2>
            <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed">
              We may suspend or terminate your account for violation of these terms. You may cancel your subscription at any time through your account settings. Upon termination, your right to use the Service ceases immediately.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-medium text-gray-800 dark:text-gray-200 mb-3">10. Contact</h2>
            <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed">
              For questions about these Terms, contact us at legal@ailisting.com.
            </p>
          </section>
        </div>
      </div>
      <Footer />
    </div>
  )
}
